config/routes.rb
Losestudiantes::Application.routes.draw do

  resources :estudiantes
  root :to => redirect('/estudiantes')

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  
  def index
    @estudiantes = Estudiante.all
  end
  
  def show
    id=params[:id]
    @estudiante = Estudiante.find(id)
  end
  
  def new
  end
  
  def create
    @estudiante = Estudiante.create!(params[:estudiante])
    redirect_to estudiantes_path
  end
  
  def edit
    @estudiante = Estudiante.find params[:id]
  end

  def update
    @estudiante = Estudiante.find params[:id]
    @estudiante.update_attributes!(params[:estudiante])
    flash[:notice] = "#{@estudiante.nombre} fue actualizado!!"
    redirect_to estudiante_path(@estudiante)
  end
  
  def destroy
    @estudiante = Estudiante.find params[:id]
    @estudiante.destroy
    flash[:notice] = "La alumna #{@estudiante.nombre} fue borrada!!"
    redirect_to estudiantes_path
  end
end




  
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/estudiantes/edit.html.haml
%h2 Editar Estudiante #{@estudiante.nombre}
=form_tag estudiante_path(@estudiante), :method =>:put do
  = label :estudiante, :nombre, 'Nombre'
  = text_field :estudiante, :nombre
  = label :estudiante, :carrera, 'Carrera'
  = select :estudiante, :carrera, ['Redes', 'Tele', 'Control', 'Mecanica']

  = label :estudiante, :fecha_ingreso, 'Ingresado en'
  = date_select :estudiante, :fecha_ingreso
  %br
  %br
  = submit_tag 'Actualizar'

app/views/estudiantes/index.html.haml
%h2 Listado de alumnos
%table#estudiantes
  %thead
    %tr
      %th Nombre
      %th Carrera
      %th Fecha Ingreso a la U
      %th Mas informacion
    %tbody
      - @estudiantes.each do |estudiante|
        %tr
          %td= estudiante.nombre
          %td= estudiante.carrera
          %td= estudiante.fecha_ingreso
          %td= link_to "Mas sobre #{estudiante.nombre}", estudiante_path(estudiante)
          
= link_to 'Agregar nuevo estudiante', new_estudiante_path

app/views/estudiantes/new.html.haml
%h2 Nuevo Estudiante!
=form_tag estudiantes_path, :method =>:post do
  = label :estudiante, :nombre, 'Nombre'
  = text_field :estudiante, :nombre
  = label :estudiante, :carrera, 'Carrera'
  = select :estudiante, :carrera, ['Redes', 'Tele', 'Control', 'Mecanica']

  = label :estudiante, :fecha_ingreso, 'Ingresado en'
  = date_select :estudiante, :fecha_ingreso
  %br
  %br
  = submit_tag 'Guardar'

app/views/estudiantes/show.html.haml
%h2 Detalles sobre #{@estudiante.nombre}
%ul#detalles
  %li
    Carrera:
    =@estudiante.carrera
  %li
    Ingresado el:
    = @estudiante.fecha_ingreso.strftime("%B %d, %Y")
%h3 Observaciones:
%p#observaciones= @estudiante.observaciones
= link_to 'Regresar a la lista de estudiantes',estudiantes_path
= link_to 'Editar', edit_estudiante_path(@estudiante)
= button_to 'Eliminar', estudiante_path(@estudiante), :method => :delete, :confirm => 'Estas seguro?'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Mi Aplicacion en Rails
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]

    =yield